### ISSUE TITLE
Ensure a list of active extensions are findable

### ISSUE THREAD

**Issue by metasean** [gundb/gundb.github.io#13]
Ensure active gun extensions are findable.

At the moment, a google docs will suffice - https://docs.google.com/spreadsheets/d/13vZfC2ROlZAJJbM5DiIShEjfGhHxOChYUJSXqzo-8mc/edit?usp=sharing

**Comment by PsychoLlama** [comment]
Since we've created the [modules](https://github.com/amark/gun/wiki/Modules) wiki page, I think we've solved this issue...
