### ISSUE TITLE
Google Analytics not included

### ISSUE THREAD

**Issue by PsychoLlama** [gundb/gundb.github.io#16]
It seems the google analytics logic was left out. Metasean assigned per our conversation.

**Comment by metasean** [comment]
@alvaro911 & @PsychoLlama - What did you guys do?  

I was expecting to update a page or two.  Instead I had to recreate the actual analytics script and reinsert it to every html page. (And I'm hoping I didn't miss any.)

**Comment by PsychoLlama** [comment]
Well, we kinda rebuilt... everything...
