### ISSUE TITLE
404 link in http://gun.js.org/docs/gun.html

### ISSUE THREAD

**Issue by sudodoki** [gundb/gundb.github.io#22]
https://github.com/gundb/gundb.github.io/blob/4c660851cd06d90ff1e00a1009ab41123f498c40/docs/gun.html#L52 features link to `Modules`, which resolves to http://gun.js.org/docs/Modules, which 404s.

**Comment by amark** [comment]
Thanks :) What are you working on and building? The world is such a better place when anybody, like you, has the power to make little things better for anybody/everybody else. Keep rocking it!

**Comment by sudodoki** [comment]
Thanks for quick merge. 🎉 

>What are you working on and building?

Just a rando on the internet, wondering about current state of p2p in javascript and had colleague point me out to gun.

**Comment by amark** [comment]
Thanks for the quick fix! Nice :) well definitely keep in touch and let me know what you build!
