### ISSUE TITLE
Website updates still pending from amark/gun/pull/92

### ISSUE THREAD

**Issue by metasean** [gundb/gundb.github.io#9]
More discussion and detail over at amark/gun/pull/92, 

Known website (https://github.com/gundb/gundb.github.io) updates:
- [ ] incorporate @kevinsimper 's drop shadow pull request
- [x] @MetaSean - add examples page _(finalizing and pushing on Monday, 2015-10-18)_
- [x] add FAQ page

**Comment by PsychoLlama** [comment]
Hey, looks like we never got this resolved. Since we've redesigned our websites, the drop shadow is no longer applicable :disappointed: are we still thinking about the FAQ? That might be a good page for our wiki...

**Comment by metasean** [comment]
Added an empty FAQs page, via the sidebar.  As we run across FAQs, we need to add them to the page :-)

**Comment by PsychoLlama** [comment]
Thanks Sean!
